### Site info:
title: 我思故我在
tagline: 享受思考的乐趣
author: junch
name: Jun Chen
email: junc76@gmail.com
description: "文艺老青年的唠叨" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junch.github.com" # the base hostname & protocol for your site


### Personal info and site tools info:
github_username:  junch
disqus_shortname: junch
weibo_username: ""
douban_username: ""
favicon:     "/images/favicon.ico"
aboutme: "建筑结构工程师，程序员，宅男，老公，儿子他爸，读者，股民，偶尔的跑者" # these are shown on aboutme-sidebar.
aboutme_photo: "https://avatars3.githubusercontent.com/u/3397616?v=3&s=400" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "时光机"
      Blogroll: "博客链接"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "旧篇"
      Next: "新篇"
      PostedInCategories: "分类:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "

### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
gems: [jekyll-paginate]

kramdown:
    input: GFM
    hard_wrap: false